### ISSUE TITLE
Add unit tests to the code

### ISSUE THREAD

**Issue by rlopezcoto** [IAA-CSIC/MUTIS#13]
Currently no unit tests are added

**Comment by Bultako** [comment]
Ok, now we have some tests.
Also [codecov](https://app.codecov.io/gh/IAA-CSIC/MUTIS/) service implemented with the badge in the README.
Now, let's make some progress in the coverage.

**Comment by Bultako** [comment]
Done in https://github.com/IAA-CSIC/MUTIS/pull/14
