### ISSUE TITLE
plot_times() function does not exist

### ISSUE THREAD

**Issue by rlopezcoto** [IAA-CSIC/MUTIS#3]
`plot_times()` function from the docs
https://github.com/IAA-CSIC/MUTIS/blob/c81076232a649851a014b4c6848f038edc65682d/docs/_build/html/recipes/mutis_workflow.html#L1103

does not exist

**Comment by juanep97** [comment]
There are some functions missing in correlations/core.py and correlations/methods.py. I'm trying to add them from my version it but first I have to figure out how to use github, gimme a min.

**Comment by Bultako** [comment]
fixed in PR #5
